#!/usr/bin/env bash
#
# gen_rgbmap.sh -- extract ConEmu's ClrMap[8] and RgbMap[256] verbatim into vendor/ConEmuRgbMap.h.
#
# Why a generator instead of a hand-written table: RgbMap is 256 literals that must match upstream
# exactly, and the replica formula (xterm cube + greyscale ramp) is only *nearly* it -- 15 of 256
# entries disagree with a naive computation, which is precisely the kind of difference that shows up
# as "the prompt is cyan on Win7 and yellow on Win11". Anchored on the declarations, not on line
# numbers, so upstream edits above this block do not silently misalign the extraction.
#
# Usage:  src/c/conemu/gen_rgbmap.sh [ConEmu-src-dir]      (default /mnt/d/ConEmu-master/src)
#         src/c/conemu/gen_rgbmap.sh --check               (fail if the header is stale)

set -u

SELF=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P) || SELF=.
SRC=${1:-/mnt/d/ConEmu-master/src}
[ "${1:-}" = "--check" ] && SRC=${2:-/mnt/d/ConEmu-master/src}
CHECK=""
[ "${1:-}" = "--check" ] && CHECK=1

ANSI="$SRC/ConEmuHk/Ansi.cpp"
OUT="$SELF/vendor/ConEmuRgbMap.h"
[ -f "$ANSI" ] || { printf 'upstream not found: %s\n' "$ANSI" >&2; exit 1; }

BODY=$(awk '
  /static DWORD ClrMap\[8\]/ { inblock=1 }
  inblock {
    print
    if (seenRgb && $0 ~ /^\s*};/) { inblock=0 }
    if ($0 ~ /static DWORD RgbMap\[256\]/) { seenRgb=1 }
  }
' "$ANSI" | sed 's/\r$//')

if [ -z "$BODY" ]; then
  printf 'could not locate ClrMap/RgbMap in %s -- upstream moved, look before regenerating\n' "$ANSI" >&2
  exit 1
fi

NCLR=$(printf '%s\n' "$BODY" | grep -c 'static DWORD ClrMap')
NRGB=$(printf '%s\n' "$BODY" | grep -c 'static DWORD RgbMap')
NCOM=$(printf '%s\n' "$BODY" | grep -o '/\*[0-9]\+\*/' | wc -l | tr -d ' ')
[ "$NCLR" = 1 ] && [ "$NRGB" = 1 ] && [ "$NCOM" -ge 240 ] \
  || { printf 'extraction looks wrong (ClrMap=%s RgbMap=%s indexed-literals=%s), refusing to write\n' "$NCLR" "$NRGB" "$NCOM" >&2; exit 1; }

TMP=$(mktemp)
{
  printf '/*\n'
  printf ' * GENERATED by gen_rgbmap.sh from %s -- DO NOT EDIT BY HAND.\n' "$ANSI"
  printf ' *\n'
  printf ' * Verbatim excerpt of CEAnsi::ReSetDisplayParm (the two tables only). Upstream is\n'
  printf ' * Copyright (c) 2009-present Maximus5, BSD 3-Clause; the notice in ConEmuColors3.h applies\n'
  printf ' * to this excerpt as well.\n'
  printf ' *\n'
  printf ' * RgbMap[0..15] are *console attributes*, not COLORREFs (ClrMap[n&7] | (n>=8?8:0));\n'
  printf ' * RgbMap[16..255] are 0x00BBGGRR. That is why the 24-bit flag is gated on "> 15".\n'
  printf ' */\n\n'
  printf '#ifndef DBCLI_CONEMU_RGBMAP_H\n#define DBCLI_CONEMU_RGBMAP_H\n\n'
  printf '#ifdef _WIN32\n#  include <windows.h>   /* DWORD */\n#else\n#  include <stdint.h>\n   typedef uint32_t DWORD;   /* so the host colour test can read the same table */\n#endif\n\n'
  printf '%s\n' "$BODY" | sed 's/^\t\t//'
  printf '\n#endif /* DBCLI_CONEMU_RGBMAP_H */\n'
} > "$TMP"

if [ -n "$CHECK" ]; then
  if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    printf 'vendor/ConEmuRgbMap.h: up to date OK\n'; rm -f "$TMP"; exit 0
  fi
  printf 'vendor/ConEmuRgbMap.h: STALE (rerun gen_rgbmap.sh) or missing\n'; rm -f "$TMP"; exit 1
fi

mkdir -p "$SELF/vendor"
mv "$TMP" "$OUT"
printf 'wrote %s (%s bytes)\n' "$OUT" "$(wc -c < "$OUT" | tr -d ' ')"
