/*[[Show RAC Inter-Connect devices stats]]*/
SET FEED OFF SEP4K ON
COL ADDR,INDX,CON_ID, NOPRINT
COL BYTES_RECEIVED,BYTES_SENT,BYTES_RCV FORMAT KMG
COL PACKETS_RECEIVED,PACKETS_SENT FORMAT TMB
COL PCT FOR PCT
COL RECEIVE_ERRORS HEAD RCV_ERRS
COL RECEIVE_DROPPED HEAD RCV_DROP
COL RECEIVE_BUF_OR HEAD RCV_BUF_OR
COL RECEIVE_FRAME_ERR HEAD RCV_FRAME_ERR
COL INST_ID HEAD INST

PRO Inter-Connect Stats:
PRO ===================
SELECT * FROM TABLE(GV$(CURSOR(
    select NVL(b.PUB_KSXPIA,'Y') "PUBLIC",a.* from sys.x$ksxpif a,sys.X$KSXPIA b
    WHERE  a.IF_NAME=b.NAME_KSXPIA(+)
    AND    a.IP_ADDR=b.IP_KSXPIA(+)
)))
ORDER BY inst_id,ip_addr;

PRO Inter-Connect Data:
PRO ===================
SELECT A.*,RATIO_TO_REPORT(BYTES_SENT+BYTES_RCV) OVER(PARTITION BY INST_ID) PCT
FROM TABLE(GV$(CURSOR(SELECT * FROM sys.X$KSXPCLIENT))) A 
WHERE BYTES_SENT+BYTES_RCV>0
ORDER BY INST_ID,2;


PRO Instance Pings:
PRO ===================
SELECT * FROM GV$INSTANCE_PING ORDER BY 1,2;