/*[[Show PL/SQL compile environment.]]*/
set feed off
BEGIN
    DBMS_OUTPUT.PUT_LINE('$$PLSCOPE_SETTINGS       = '|| $$PLSCOPE_SETTINGS);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_CCFLAGS          = '|| $$PLSQL_CCFLAGS);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_CODE_TYPE        = '|| $$PLSQL_CODE_TYPE);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_OPTIMIZE_LEVEL   = '|| $$PLSQL_OPTIMIZE_LEVEL);
    --DBMS_OUTPUT.PUT_LINE('$$PLSQL_DEBUG = '          || $$PLSQL_DEBUG);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_WARNINGS         = '|| $$PLSQL_WARNINGS);
    DBMS_OUTPUT.PUT_LINE('$$NLS_LENGTH_SEMANTICS   = '|| $$NLS_LENGTH_SEMANTICS);

    DBMS_OUTPUT.PUT_LINE('$$PLSQL_LINE             = '|| $$PLSQL_LINE);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_UNIT             = '|| $$PLSQL_UNIT);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_UNIT_OWNER       = '|| $$PLSQL_UNIT_OWNER);
    DBMS_OUTPUT.PUT_LINE('$$PLSQL_UNIT_TYPE        = '|| $$PLSQL_UNIT_TYPE);

    DBMS_OUTPUT.PUT_LINE('UID                      = '|| UID);
    DBMS_OUTPUT.PUT_LINE('USER                     = '|| USER);
    DBMS_OUTPUT.PUT_LINE('CURRENT_USER             = '|| SYS_CONTEXT('USERENV','CURRENT_USER'));
    DBMS_OUTPUT.PUT_LINE('CURRENT_SCHEMA           = '|| SYS_CONTEXT('USERENV','CURRENT_SCHEMA'));
    --some values are impacted by parameter fixed_date
    DBMS_OUTPUT.PUT_LINE('SYSDATE                  = '|| SYSDATE);
    DBMS_OUTPUT.PUT_LINE('SYSTIMESTAMP             = '|| SYSTIMESTAMP);
    DBMS_OUTPUT.PUT_LINE('CURRENT_DATE             = '|| CURRENT_DATE); 
    DBMS_OUTPUT.PUT_LINE('CURRENT_TIMESTAMP        = '|| CURRENT_TIMESTAMP);
    DBMS_OUTPUT.PUT_LINE('LOCALTIMESTAMP           = '|| LOCALTIMESTAMP);
    DBMS_OUTPUT.PUT_LINE('DBTIMEZONE               = '|| DBTIMEZONE);
    DBMS_OUTPUT.PUT_LINE('SESSIONTIMEZONE          = '|| SESSIONTIMEZONE);
    DBMS_OUTPUT.PUT_LINE('DBMS_UTILITY.GET_TIME    = '|| DBMS_UTILITY.GET_TIME||' (v$timer)');
    DBMS_OUTPUT.PUT_LINE('DBMS_UTILITY.GET_CPU_TIME= '|| DBMS_UTILITY.GET_CPU_TIME);
END;
/