/*[[List patches that have been applied in current database. Usage: @@NAME [<keyword>]
    --[[
    --]]
]]*/
WITH R AS(SELECT /*+MATERALIZE*/ MAX(PATCH_VERSION) KEEP(DENSE_RANK LAST ORDER BY PATCH_TIMESTAMP) VER FROM DBA_CLOUD_PATCH_INFO)
SELECT * FROM DBA_CLOUD_PATCH_INFO 
WHERE :V1 IS NULL AND PATCH_VERSION=(SELECT VER FROM R)
OR    :V1 IS NOT NULL AND upper(BUG_NUM||','||BUG_TITLE||','||COMPONENT_NAME||','||PATCH_VERSION) LIKE '%'||upper(:v1)||'%'
ORDER BY PATCH_TIMESTAMP DESC FETCH FIRST 300 ROWS ONLY;