/*[[Show current connection info]]*/
SELECT current_schema(),
       --pg_current_userid(),
       user,
       current_user,
       session_user,
       --definer_current_user(),
       getpgusername(),
       pg_backend_pid(),
       --pg_current_sessionid(),
       --pg_current_sessid(),
       --working_version_num(),
       inet_client_addr(),
       inet_client_port(),
       inet_server_addr(),
       inet_server_port(),
       pg_conf_load_time(),
       pg_my_temp_schema(),
       pg_listening_channels(),
       pg_postmaster_start_time(),
       getdatabaseencoding()\G