/*[[
    Show the data that generated by dbms_hprof. Usage: @@NAME {<runid>}|{<Dir> <File> [PLSQL_BLOCK]}

    Install:
        11g: @?/rdbms/admin/dbmshptab.sql
        18c: EXEC DBMS_HPROF.create_tables(force_it => TRUE);

    Example:
        @@NAME DATA_PUMP_DIR 1.txt "dbms_lock.sleep(10);dbms_session.sleep(10)"
        @@NAME 1

    A flame graph of the call tree is also generated as <cache>/hprof_<runid>.svg
    (folded stacks rendered by the 'flame' command, times in microsecs).
    The plshprof report is saved as <cache>/plshprof_<runid>.html. A <runid> has
    no trace file left to analyze, so its report is rebuilt from the raw records
    in dbmshp_trace_data, which needs 18c or a newer version.
    --[[
        @CHECK_ACCESS: dba_source={DBA_SOURCE}, all_source={ALL_SOURCE}
        @CHECK_ACCESS2: SYS.DBMS_HPROF/DBMSHP_RUNS={}
    --]]
]]*/
set feed off verify off printsize 1000
VAR cur REFCURSOR
VAR html CLOB
VAR filename VARCHAR2(100)
VAR folded CLOB
VAR svgname VARCHAR2(100)
ora _find_object "&V1" 1
col subtree_time,func_time for usmhd2

DECLARE
    run_id     INT;
    trace_id   NUMBER;
    dir        VARCHAR2(128) := :V1;
    file       VARCHAR2(100) := :V2;
    output     CLOB;
    trace_file BFILE;
    folded     CLOB;
    pos        INT := 1;
    startpos   PLS_INTEGER := 1;
    lang_ctx   PLS_INTEGER := 0;
    csid       PLS_INTEGER := 0;
    warn       PLS_INTEGER := 0;
BEGIN
    IF dir IS NULL THEN
        OPEN :cur FOR
            SELECT * FROM dbmshp_runs ORDER BY run_timestamp DESC;
    ELSE
        IF regexp_like(dir, '^\d+$') THEN
            run_id := dir;
            -- An already analyzed run has no trace file to hand to plshprof, so
            -- rebuild the report from the raw records that analyze kept in
            -- dbmshp_trace_data. runid comes from dbmshp_runnumber, not from the
            -- trace id, so resolve the trace this run was collected from first.
            $IF dbms_db_version.version >= 18 $THEN
                BEGIN
                    SELECT trace_id
                    INTO   trace_id
                    FROM   dbmshp_runs
                    WHERE  runid = run_id;

                    IF trace_id IS NOT NULL THEN
                        sys.dbms_hprof.analyze(trace_id => trace_id, report_clob => output);
                    END IF;
                EXCEPTION WHEN OTHERS THEN
                    dbms_output.put_line('Cannot generate the HTML report of runid '
                        || run_id || ', raw trace data is required: ' || sqlerrm);
                END;
            $END
            :html     := output;
            :filename := 'plshprof_' || run_id || '.html';
        ELSE
            dir := :OBJECT_NAME;
            IF file IS NULL THEN
                raise_application_error(-20001, 'Usage: ora hprof <Directory Name> <File Name> [PLSQL_BLOCK].');
            ELSIF USER != nvl(:OBJECT_OWNER, '_') THEN
                SELECT COUNT(1)
                INTO   run_id
                FROM   table_privileges
                WHERE  owner = :OBJECT_OWNER
                AND    table_name = dir;

                IF run_id = 0 THEN
                    raise_application_error(-20001,'Directory ' || dir ||' does not exist or you don''t have its access right.');
                END IF;
            END IF;

            IF :V3 IS NOT NULL THEN
                BEGIN
                    sys.dbms_hprof.start_profiling(location => dir, filename => file);
                EXCEPTION WHEN OTHERS THEN
                    raise_application_error(-20001,'Error on executing "SYS.DBMS_HPROF.start_profiling" on directory "'||dir||'": '||sqlerrm);
                END;
                BEGIN
                    EXECUTE IMMEDIATE 'BEGIN ' || regexp_replace(:V3, ';\s*$') || ';END;';
                EXCEPTION WHEN OTHERS THEN
                    sys.dbms_hprof.stop_profiling;
                    RAISE;
                END;
                sys.dbms_hprof.stop_profiling;
            END IF;

            BEGIN
                trace_file := bfilename(dir, file);
                dbms_lob.fileopen(trace_file);
            EXCEPTION WHEN OTHERS THEN
                raise_application_error(-20001, 'File ' || file || ' under directory ' || dir || ' does not exist!');
            END;

            run_id := dbms_lob.getlength(trace_file);
            IF run_id = 0 THEN
                raise_application_error(-20001, 'Cannot read file ' || file || ' under directory ' || dir || '.');
            END IF;
            /*IF DBMS_DB_VERSION.VERSION < 12 THEN
                dbms_lob.createtemporary(output, TRUE);
                dbms_lob.loadclobfromfile(output, trace_file, DBMS_LOB.LOBMAXSIZE, startpos, pos, csid, lang_ctx, warn);
            END IF;*/
            dbms_lob.fileclose(trace_file);

            run_id := sys.dbms_hprof.analyze(location => dir, filename => file);
            $IF dbms_db_version.version > 11 $THEN
                sys.dbms_hprof.analyze(location => dir, filename => file, report_clob => output);
                file := NULL;
            $END

            :html     := output;
            :filename := nvl(file, 'plshprof_' || run_id || '.html');
            dbms_output.put_line('Runid is ' || run_id ||', file size is '||length(output)||' bytes.');
        END IF;

        -- Fold the profiler call graph into "stack self_us" lines for the flame
        -- graph: each node's self time lands once, on its dominant caller chain
        -- (the parent with the largest subtree). dbmshp_parent_child_info is a
        -- DAG, not a tree (a child may have several parents), so walking every
        -- path with CONNECT BY would count shared nodes repeatedly.
        dbms_lob.createtemporary(folded, TRUE);
        DECLARE
            TYPE str_tab IS TABLE OF VARCHAR2(32767);
            TYPE num_tab IS TABLE OF NUMBER;
            stacks str_tab;
            selfs  num_tab;
        BEGIN
            WITH node AS
             (SELECT fi.symbolid,
                     trim('.' FROM fi.owner || '.' || fi.module || '.' || nullif(fi.function, fi.module))
                     || decode(fi.line#, 0, '', ' (Line #' || fi.line# || ')') AS frame,
                     nvl(fi.function_elapsed_time, 0) AS self_us
              FROM   dbmshp_function_info fi
              WHERE  fi.runid = run_id),
            dom AS
             (SELECT pci.childsymid AS symbolid,
                     max(pci.parentsymid) KEEP (DENSE_RANK LAST ORDER BY pci.subtree_elapsed_time) AS parentsymid
              FROM   dbmshp_parent_child_info pci
              WHERE  pci.runid = run_id
              GROUP  BY pci.childsymid),
            tree (symbolid, stack, self_us) AS
             (SELECT n.symbolid, n.frame, n.self_us
              FROM   node n
              WHERE  NOT EXISTS (SELECT 1 FROM dom d WHERE d.symbolid = n.symbolid)
              UNION ALL
              SELECT n.symbolid, t.stack || ';' || n.frame, n.self_us
              FROM   tree t
              JOIN   dom  d ON d.parentsymid = t.symbolid
              JOIN   node n ON n.symbolid = d.symbolid)
            SELECT stack, sum(self_us) AS self_us
            BULK COLLECT INTO stacks, selfs
            FROM   tree
            GROUP  BY stack;

            FOR i IN 1 .. stacks.COUNT LOOP
                IF selfs(i) > 0 THEN
                    dbms_lob.writeappend(folded, length(ltrim(stacks(i), ';')) + length(to_char(round(selfs(i)))) + 2,
                                         ltrim(stacks(i), ';') || ' ' || round(selfs(i)) || chr(10));
                END IF;
            END LOOP;
        END;
        :folded  := folded;
        :svgname := 'hprof_' || run_id;
        dbms_lob.freetemporary(folded);

        OPEN :cur FOR
            WITH src AS
             (SELECT /*+MATERIALIZE no_merge(u) opt_param('cursor_sharing' 'force')*/
                     u.*, extractvalue(b.column_value,'//TEXT') text
              FROM   (SELECT * FROM dbmshp_function_info WHERE runid = run_id) u,
                     TABLE(xmlsequence(extract(dbms_xmlgen.getxmltype(
                       q'[SELECT regexp_substr(ltrim(TEXT,chr(9)||' '),'[^'||chr(10)||']+') text
                          FROM &CHECK_ACCESS
                          WHERE OWNER=']' || owner ||
                          ''' AND line=''' || line# ||
                          ''' AND NAME=''' || module ||
                          ''' AND TYPE=''' || replace(type,' SPEC') || ''''),'//ROW')))(+) b),
            hier AS
             (SELECT rpad(' ', (LEVEL - 1) * 2, ' ') || name AS hname,
                     a.*,
                     (SELECT max(subtree_elapsed_time) FROM dbmshp_parent_child_info WHERE runid = run_id) max_time
              FROM   (SELECT fi.symbolid,
                             pci.parentsymid,
                             trim('.' FROM fi.owner || '.' || fi.module || '.' || nullif(fi.function, fi.module))
                             || decode(line#, 0, '', ' (Line #' || line# || ')') AS name,
                             sql_id,
                             nvl(sql_text,text) text,
                             nvl(pci.subtree_elapsed_time, fi.subtree_elapsed_time) AS subtree_time,
                             nvl(pci.function_elapsed_time, fi.function_elapsed_time) AS func_time,
                             nvl(pci.calls, fi.calls) AS calls
                      FROM   src fi
                      LEFT   JOIN dbmshp_parent_child_info pci
                      ON     fi.runid = pci.runid
                      AND    fi.symbolid = pci.childsymid) a
              CONNECT BY a.parentsymid = PRIOR a.symbolid
              START  WITH a.parentsymid IS NULL
              ORDER  SIBLINGS BY subtree_time DESC)
            SELECT hname function_name,
                   subtree_time,
                   to_char(100*subtree_time/max_time,'990.00')||'%' "Subtree(%)",
                   func_time,
                   to_char(100*func_time/max_time,'990.00')||'%' "Func(%)",
                   calls,sql_id,'|' "|",text
            FROM   (SELECT a.*, rownum r FROM hier a)
            WHERE  greatest(subtree_time,func_time)*10000/max_time>=1
            ORDER  BY r;
    END IF;
END;
/
print cur
save html filename
flame folded svgname countname=us title=DBMS_HPROF
