/*[[
    Show the data that generated by dbms_profiler. Usage: @@NAME {[<runid>] [<sort_by>]}|<PL/SQL Block>

    Install DBMS_PROFILER : @?/rdbms/admin/profload.sql  --as sysdba
    Install record tables : @?/rdbms/admin/proftab.sql   --on target schema to run the profile

    Also refer to dbcli/sqlplus/profrep.sql to generate more report details.
    
    Example:
        @@NAME "dbms_lock.sleep(10);dbms_session.sleep(10)"
    --[[
        @ALIAS: profiler
        @CHECK_ACCESS: dba_source={DBA_SOURCE}, all_source={ALL_SOURCE}
        @CHECK_ACCESS2: SYS.DBMS_PROFILER/PLSQL_PROFILER_DATA={}
        &V2: default={TOTAL_TIME}
    --]]
]]*/
set feed off
COL total_time,MIN_TIME,MAX_TIME for usmhd2
VAR cur REFCURSOR
DECLARE
    run_id INT;
    c      VARCHAR2(100);
BEGIN
    IF :V1 IS NULL THEN
        OPEN :cur FOR
            SELECT RUNID,RELATED_RUN,RUN_OWNER,RUN_DATE,RUN_COMMENT,LTRIM(RTRIM(to_char(NUMTODSINTERVAL(RUN_TOTAL_TIME*1E-9,'SECOND')),'0.'),'0+') RUN_TIME,RUN_SYSTEM_INFO,RUN_COMMENT1,SPARE1
            FROM PLSQL_PROFILER_RUNS ORDER BY RUNID DESC;
    ELSE
        IF regexp_like(:V1,'^\d+$') THEN
            run_id:=:V1;
        ELSE
            c      := 'DBCLI_'||round(dbms_random.value(1e5,1e6));
            run_id := SYS.DBMS_PROFILER.start_profiler(c);
            BEGIN
                EXECUTE IMMEDIATE 'BEGIN '||regexp_replace(:V1,';\s*$')||';END;';
                SYS.DBMS_PROFILER.FLUSH_DATA;
                run_id := SYS.DBMS_PROFILER.stop_profiler;
            EXCEPTION WHEN OTHERS THEN
                run_id := SYS.DBMS_PROFILER.stop_profiler;
                RAISE;
            END;
            select max(runid) into run_id from PLSQL_PROFILER_RUNS where RUN_COMMENT=c;
            dbms_output.put_line('Runid is '||run_id);
        END IF;

        OPEN :cur FOR
            WITH SRC AS
             (SELECT /*+MATERIALIZE no_merge(u)*/
                    U.*, EXTRACTVALUE(b.COLUMN_VALUE,'//TEXT') text,EXTRACTVALUE(b.COLUMN_VALUE,'//LINE')+0 line#,EXTRACTVALUE(b.COLUMN_VALUE,'//SUB_NAME') subname
              FROM  (SELECT * FROM PLSQL_PROFILER_UNITS WHERE RUNID = run_id) u,
                     TABLE(XMLSEQUENCE(EXTRACT(dbms_xmlgen.getxmltype(
                         q'[SELECT line,ltrim(TEXT,chr(9)||' ') text,
                                   regexp_substr(regexp_substr(text,'(procedure|function) +[^ \(]+',1,1,'i'),'[^ ]+',1,2) sub_name
                           FROM &CHECK_ACCESS
                           WHERE ']'||UNIT_TYPE ||''' NOT LIKE ''ANONYMOUS%'' AND OWNER=''' ||unit_owner ||
                                ''' AND NAME=''' || unit_name ||
                                ''' AND TYPE=''' || unit_type ||''''),'//ROW')))(+) B),
            rs as(
                SELECT /*+ORDERED use_hash(dat src) MATERIALIZE*/
                         src.unit_owner, src.unit_name, dat.line#, dat.TOTAL_OCCUR,unit_number,
                         rownum r,
                         dat.TOTAL_TIME * 1E-3 TOTAL_TIME,
                         dat.MIN_TIME * 1E-3 MIN_TIME,
                         dat.MAX_TIME * 1E-3 MAX_TIME,
                         regexp_substr(src.text,'[^'||chr(10)||']+') text
                FROM   PLSQL_PROFILER_DATA dat
                JOIN   src
                USING  (RUNID, UNIT_NUMBER)
                WHERE  RUNID = run_id AND dat.line#=nvl(src.line#,dat.line#))
            SELECT * FROM (
                SELECT unit_number unit#,unit_owner,unit_name,subname,line#,total_occur,total_time,min_time ,max_time,text
                FROM(
                    SELECT /*+ordered use_hash(rs src)*/
                        rs.*,row_number() over(partition by rs.r order by src.line# desc) seq, src.subname
                    FROM  rs, src
                    WHERE rs.unit_number=src.unit_number(+)
                    AND   rs.line#>=src.line#(+)
                    AND   src.subname(+) IS NOT NULL
                ) WHERE SEQ=1
                ORDER BY &V2 DESC NULLS LAST
            ) WHERE ROWNUM<=100;
    END IF;
END;
/
    